### PR TITLE
Windows Executable creator

### PR DESCRIPTION
**Pull request by rocas777**
Created a bat script that automates the creation of a exe file installer and exe file executable.
In the current version the standalone jar needs to be placed manually at the script folder with the name edumips for the script to work.
The output is in the Output folder. It is a standalone executable that can be used to install the program on the machine.

### CODE REVIEW

**Comment by rocas777** [comment]
this commit fixes #302

**Comment by lupino3** [comment]
Hi @rocas777, thanks a lot for this feature!

I read a bit more about the new `jpackage` jdk tool, and I would prefer to use it rather than depending on launch4j.

Could you please modify the scripts to use it?

The user needs to have WIX tools installed (https://github.com/wixtoolset/wix3/releases, we can just document this in the developer docs) and use JDK 14+ (e.g., AdoptOpenJDK 15: https://adoptopenjdk.net/?variant=openjdk15&jvmVariant=hotspot). If those requirements are satisfied, we can create an MSI by running the following commands:

```
> ./gradlew jar
[...]
> jpackage.exe --main-jar edumips64-1.2.7.1.jar --input .\build\libs\ --app-version 1.2.8 --name EduMIPS64 --description "Educational MIPS64 CPU Simulator" --vendor "EduMIPS64 Development Team" --copyright "Copyright 2020, EduMIPS64 development Team" --license-file .\LICENSE --win-shortcut --win-dir-chooser --win-menu --type msi --icon .\src\main\resources\images\ico.ico --win-per-user-install
```

The advantages I see with the `jpackage` approach are the following:

- it automatically bundles the portions of JRE needed by EduMIPS64 (no need to download it or to check a JRE copy into our repository);
- it is an official JDK tool;
- it is pretty simple to use (a single command with a few command-line arguments);

What do you think?

(p.s. I'll attach the ICO file to the issue, can't attach to a PR)

**Comment by rocas777** [comment]
I made the script a while ago but i forgot to make a pull request. Only noticed that when you posted about the jpackage and i decided to make the pull request anyway.
I will give it a try.

**Comment by lupino3** [comment]
Thanks a million!

**Comment by lupino3** [comment]
Thanks a lot! I'd suggest to abandon this pull request and create a new one.

**Pull request closed without merging**
