### PR TITLE
Webapp update

### PR DESCRIPTION
**Pull request by smallg0at**
# Updating Webapp

## Changes

- Redesigned UI placements, allowing this thing to at least look like an IDE
- Adds dark mode, which will always match system / browser preference on this. Not manually tunable.
- Now user is allowed to manually specify how many step to run in Multi-Step
- Version code gets moved to the Help dialog
- New: An error list will now get shown

## Known Issue

- Due to the nature of EduMips64's logo, its contrasts are terrible in dark mode
- When entering `dmulu `(space), an worker error will pop up

## Screenshots

image

image

### CODE REVIEW

**Comment by lupino3** [comment]
Also, there is a large number of codacy issues. Most of them are pretty minor though.
It would be nice if you could fix at least some of them, but if you can't that's fine, please open an issue and we'll deal with it later - the redesign is very cool and I'd like to get it merged soon!

Thanks!

**Comment by smallg0at** [comment]
image

Threw in an error list view

**Comment by smallg0at** [comment]
So it's finished. Unfortunately, Codacy isn't happy with how my formatter worked, so those issues will be ignored anyway.

**Comment by smallg0at** [comment]
@lupino3 Currently warnings will block execution, is this intended behavior?

**Comment by lupino3** [comment]
> @lupino3 Currently warnings will block execution, is this intended behavior?

No, it's not intended. Please open an issue so that warnings become non-blocking in the Web UI. Thanks!

**Comment by lupino3** [comment]
Love the new look, thanks! Please address the multi-step comment I left in the code and I'll merge the PR. Thanks!!

**Comment by smallg0at** [comment]
> Love the new look, thanks! Please address the multi-step comment I left in the code and I'll merge the PR. Thanks!!

I'm unable to locate that

**Comment by smallg0at** [comment]
Left the code for enabling execution while warnings present in there, in commented form with a TODO. Worker refuses to execute that on its side.

**Comment by lupino3** [comment]
That's ok, no worries. Thanks for this massive contribution!!

**Pull request merged**
